# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: master

jobs:
- job: windows
  pool: 
    vmImage: 'windows-2019'
  steps:
      - script: 'call .azure/internal/build.bat'
        displayName: Build
          
