# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- job: windows
  pool: {vmImage: 'windows-2019'}
  steps: 
    - ${{ if eq(parameters.msagent, 'true') }}:
      - task: BatchScript@1
        displayName: 'Install VS 2017'
        inputs:
          filename: '.azure/internal/vs_install.bat'

          modifyEnvironment: true

      - task: BatchScript@1
        displayName: 'Install Deps'
        inputs:
          filename: '.azure/build_pytorch.bat'

          modifyEnvironment: true

      - task: BatchScript@1
        enabled: false
        displayName: 'Environment fix'
        inputs:
          filename: '.azure/internal/env_fix.bat'

          modifyEnvironment: false

      - task: BatchScript@1
        displayName: 'Install 7Zip'
        inputs:
          filename: '.azure/internal/7z_install.bat'
          modifyEnvironment: true
      
      - task: BatchScript@1
        displayName: 'Install Cuda'
        inputs:
          filename: '.azure/internal/cuda_install.bat'
          modifyEnvironment: true
      - script: |
        taskkill /im nvcc.exe /f || ver > NUL
        taskkill /im sccache.exe /f || ver > NUL
        taskkill /im cl.exe /f || ver > NUL
        taskkill /im ninja.exe /f || ver > NUL
        taskkill /im link.exe /f || ver > NUL
        taskkill /im cmake.exe /f || ver > NUL
        taskkill /im conda-build.exe /f || ver > NUL
        displayName: 'Cleaning unclosed processes'
