# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: master

- job: windows
  pool: {vmImage: 'windows-2019'}
  steps: 
      - task: BatchScript@1
        displayName: 'Install VS 2017'
        inputs:
          filename: '.azure/internal/build.bat'
          modifyEnvironment: true
